name: Build Docker Image

on:
  push:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.19
      - name: Static Check
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          min-go-version: 1.19
          install-go: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.1
        with:
          tags: type=raw,value=latest
          images: ${{ env.REGISTRY }}/slntopp/nocloud/operator

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
